### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by demanuPL** [MeFisto94/snd-usb-sinn7#5]
I still have this building error and I don't know how to fix it

`
Creating symlink /var/lib/dkms/snd-usb-sinn7/0.0.1/source ->
                 /usr/src/snd-usb-sinn7-0.0.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.4.0-48-generic KVERSION=5.4.0-48-generic CONFIG_SND_USB=y CONFIG_SND_USB_AUDIO=m -C /lib/modules/5.4.0-48-generic/build M=/var/lib/dkms/snd-usb-sinn7/0.0.1/build modules...(bad exit status: 2)
ERROR (dkms apport): binary package for snd-usb-sinn7: 0.0.1 not found
Error! Bad return status for module build on kernel: 5.4.0-48-generic (x86_64)
Consult /var/lib/dkms/snd-usb-sinn7/0.0.1/build/make.log for more information.
DKMS make.log for snd-usb-sinn7-0.0.1 for kernel 5.4.0-48-generic (x86_64)
czw, 8 paź 2020, 15:14:03 CEST
make: Wejście do katalogu '/usr/src/linux-headers-5.4.0-48-generic'
  CC [M]  /var/lib/dkms/snd-usb-sinn7/0.0.1/build/chip.o
  CC [M]  /var/lib/dkms/snd-usb-sinn7/0.0.1/build/pcm.o
/var/lib/dkms/snd-usb-sinn7/0.0.1/build/pcm.c: In function ‘sinn7_pcm_prepare’:
/var/lib/dkms/snd-usb-sinn7/0.0.1/build/pcm.c:534:3: error: implicit declaration of function ‘setup_timer’; did you mean ‘del_timer’? [-Werror=implicit-function-declaration]
  534 |   setup_timer(rt->timer, sinn7_timer_interrupt, (unsigned long)rt);
      |   ^~~~~~~~~~~
      |   del_timer
/var/lib/dkms/snd-usb-sinn7/0.0.1/build/pcm.c: At top level:
/var/lib/dkms/snd-usb-sinn7/0.0.1/build/pcm.c:599:10: error: ‘snd_pcm_lib_mmap_vmalloc’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_mmap_iomem’?
  599 |  .mmap = snd_pcm_lib_mmap_vmalloc,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
      |          snd_pcm_lib_mmap_iomem
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:273: /var/lib/dkms/snd-usb-sinn7/0.0.1/build/pcm.o] Błąd 1
make: *** [Makefile:1734: /var/lib/dkms/snd-usb-sinn7/0.0.1/build] Błąd 2
make: Opuszczenie katalogu '/usr/src/linux-headers-5.4.0-48-generic'

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.4.0-48-generic KVERSION=5.4.0-48-generic CONFIG_SND_USB=y CONFIG_SND_USB_AUDIO=m -C /lib/modules/5.4.0-48-generic/build M=/var/lib/dkms/snd-usb-sinn7/0.0.1/build modules...(bad exit status: 2)
ERROR (dkms apport): binary package for snd-usb-sinn7: 0.0.1 not found
Error! Bad return status for module build on kernel: 5.4.0-48-generic (x86_64)
Consult /var/lib/dkms/snd-usb-sinn7/0.0.1/build/make.log for more information.
`
